apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecret }}
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.secretRefName }}
            - configMapRef:
                name: {{ .Values.deployment.configMapRefName }}
