apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    chart: cert-manager
  - repoURL: https://charts.jetstack.io
    targetRevision: 1.15.3
    helm:
      valueFiles:
      - $values/charts/cert-manager/values.yaml
  - repoURL: https://github.com/dainetech/argocd.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true