apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.16.6
    helm:
      valueFiles:
      - $values/charts/promtail/values.yaml
  - repoURL: https://github.com/dainetech/argocd.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true