defaultAuthMethod:
  enabled: true
  namespace: "web-app"
  allowedNamespaces: []
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: "fakeapp"
    serviceAccount: default
    tokenAudiences: [vault]

  # Vault JWT auth method specific configuration
defaultVaultConnection:
  enabled: true
  address: "http://vault-internal.vault.svc.cluster.local:8200"
  skipTLSVerify: false