global:
  enabled: true
  namespace: "vault"
server:
  dev:
    enabled: true
    devRootToken: "root"
  standalone:
    enabled: true
injector:
  enabled: true
  replicas: 1
  port: 8090
  leaderElector:
    enabled: true
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.4.2"
    pullPolicy: IfNotPresent
  agentImage:
    repository: "hashicorp/vault"
    tag: "1.17.3"
  agentDefaults:
    cpuLimit: "500m"
    cpuRequest: "250m"
    memLimit: "128Mi"
    memRequest: "64Mi"
ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200
