global:
  enabled: true
  namespace: "vault"
server:
  dev:
    enabled: true
    devRootToken: "root"
  standalone:
    enabled: true
injector:
  enabled: false
ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200
